### PR TITLE
REL: Release v0.4.1.

### PR DESCRIPTION
**Pull request by ssanderson**

### CODE REVIEW

**Comment by ssanderson** [comment]
@rgbkrk anything besides this needed in source for a release?

**Comment by rgbkrk** [comment]
My last release commit changed these files, including CHANGES.md: https://github.com/cloudpipe/cloudpickle/commit/10b4b483d0acb1c3325c0ec0b68fdb5212390673

**Comment by ssanderson** [comment]
Updated the `__version__` and `CHANGES.md`.

**Comment by rgbkrk** [comment]
Most excellent!

**Comment by rgbkrk** [comment]
Tag it, ship it. 😄  :shipit:

**Comment by mrocklin** [comment]
I think that this project wins as the project with the largest number of people that have personally gone through a release process.  It seems like we add a new release manager every time :)

**Comment by mrocklin** [comment]
Or at least highest fraction if not absolute largest.

**Comment by ssanderson** [comment]
```
(cloudpickle-test) [~]$ pip uninstall -y cloudpickle && pip install --no-cache-dir cloudpickle && python -c'import cloudpickle; print("Version is: ", cloudpickle.__version__)'
Uninstalling cloudpickle-0.4.1:
  Successfully uninstalled cloudpickle-0.4.1
Collecting cloudpickle
  Downloading cloudpickle-0.4.1-py2.py3-none-any.whl
Installing collected packages: cloudpickle
Successfully installed cloudpickle-0.4.1
Version is:  0.4.1
```

**Comment by ssanderson** [comment]
https://github.com/cloudpipe/cloudpickle/releases/tag/v0.4.1

**Pull request merged**
