### PR TITLE
Fix downstream CI

### PR DESCRIPTION
**Pull request by ogrisel**
To make it independent of #431.

### CODE REVIEW

**Comment by pierreglaser** [comment]
OK, I got the loky and ray test suites to pass, but I think I'm getting a possible regression for Python 3.7 with distributed: in particular, `test_pickle_empty` fails (but **note that it passes on Python 3.8**). Maybe @jakirkham has an idea? Will keep investigating ASAP.

**Comment by jakirkham** [comment]
Is it possible we are just getting an old version of Dask + Distributed? We released `2021.09.0` last Friday

**Comment by pierreglaser** [comment]
If I am not mistaken, we're testing against the main GitHub branch of distributed and not pinned release.

**Comment by jakirkham** [comment]
Are we installing `pickle5` in that job or is it not included?

**Comment by jakirkham** [comment]
Ok think I know what is going on there. Submitted PR ( https://github.com/dask/distributed/pull/5303 ), which seems to fix it for me locally (though please recheck). Will see what others think of that proposal.

**Comment by pierreglaser** [comment]
Thanks a lot @jakirkham, indeed this test passes using your dask distributed fork and the cloudpickle of this PR!

**Comment by jakirkham** [comment]
Great! Thank you Pierre 😄 Have prodded some folks to review that PR 🙂

**Comment by pierreglaser** [comment]
Mmh, I'm getting another error from the `distributed` test suite: `test_dont_steal_unknown_functions` just failed. Is this test known to be flaky? Is this likely (un)related to `cloudpickle`? @jakirkham may I quickly pick your brain again?

**Comment by pierreglaser** [comment]
Re-launching the CI to see how flaky this failure is.

**Comment by jakirkham** [comment]
It is somewhat flaky ( https://github.com/dask/distributed/issues/3574 ), but it looks like a fails fairly infrequently (seeing very few references to it). If it's causing us issues, we could skip here or I could propose skipping upstream. WDYT?

**Comment by pierreglaser** [comment]
Thanks again @jakirkham. I'll skip the test directly in cloudpickle, I'm unsure of the importance of this test for distributed. I've also skipped `test_pickle_empty` so that dask/distributed#5303 does not block us from releasing cloudpickle.

However, because `test_pickle_empty` is serialization related, we should not skip it forever, and as soon as we merge this PR, I'll open another one that will the skipping of `test_pickle_empty` and that we shall merge once dask/distributed#5303 gets merged.

**Comment by jakirkham** [comment]
At some level it likely uses `pickle` for some things. That said, it is at best indirectly relevant for `cloudpickle`. Skipping it long term shouldn't cause any issues

Agree it would be good to get `test_pickle_empty` fixed and tested again here

**Comment by pierreglaser** [comment]
I hope that `cloudpickle` is not the original root behind `test_dont_steal_unknown_functions`'s flakiness :D

**Comment by jakirkham** [comment]
Hehe I highly doubt that 😄

Distributed testing is hard. I think the test suite has gotten more robust especially over the past couple years, but there remain tricky issues like that test 😅

**Comment by ogrisel** [comment]
Thank you very much @pierreglaser and @jakirkham for fixing the CI! Merging!

I think we can release cloudpickle!

**Comment by jakirkham** [comment]
Since `test_pickle_empty` was fixed in upstream Dask, have readded testing of it in PR ( https://github.com/cloudpipe/cloudpickle/pull/442 )

**Pull request merged**
