### PR TITLE
WIP -- straight copy of cloudpickle in pyspark made compatible with 3.x

### PR DESCRIPTION
**Pull request by sdegryze**
source copied from https://github.com/davies/spark/blob/python3/python/pyspark/cloudpickle.py
added Python 3.3 and 3.4 to .travis.yml
see issue #10

### CODE REVIEW

**Comment by rgbkrk** [comment]
Ha! I just added this directly locally.

**Comment by rgbkrk** [comment]
Since a bunch of code was removed in this update, we should consider what we should do with this.

I'm of the opinion that we drive forward with removing a lot of the legacy code, adding it back as necessary. There are a lot of improved pickling bits within numpy and surrounding projects that I think can be relied on. Many of the deleted bits in here are support for Python < 2.6.

**Comment by ogrisel** [comment]
+1 with @rgbkrk's comments.

**Comment by rgbkrk** [comment]
Closing in favor of #24.

**Pull request closed without merging**
