### PR TITLE
FIX pypy3 support for method descriptors

### PR DESCRIPTION
**Pull request by ogrisel**
Fix for #50.

### CODE REVIEW

**Comment by ogrisel** [comment]
@mrocklin this test was introduced in your last PR. Can you please give a quick look at this complementary fix?

**Comment by mrocklin** [comment]
This looks innocuous to me.

**Comment by rgbkrk** [comment]
Travis passed while codecov did not. Not sure how to interpret the codecov page.

**Comment by ogrisel** [comment]
> Travis passed while codecov did not. Not sure how to interpret the codecov page. Is it a failure because coverage decreased?

Yes. I think the threshold is too sensitive. Alternatively we might want to investigate if there is a way to consolidate the coverage of the tests run on all the python versions run by travis on a single branch.

Maybe later, let's merge this ;)

**Comment by rgbkrk** [comment]
:shipit:

**Pull request merged**
