### PR TITLE
Add the missing buffer_callback argument

### PR DESCRIPTION
**Pull request by suquark**
Since we are using `cloudpickle_fast.py` for Python3.8+, it should also keep the same pickle interface. `buffer_callback` is actually critical for pickle5 fast serialization, and adding this will not break cloudpickle's interface.

### CODE REVIEW

**Comment by pcmoritz** [comment]
This looks great :)

**Comment by pcmoritz** [comment]
Another thought: Do we need to make sure that the pickler we use actually supports this keyword? Or is this codepath only supported on ones that do (>= 3.8 and the pickle5 backport)?

**Comment by suquark** [comment]
@pcmoritz Because cloudpickle_fast is designed for python3.8+, so the assumption is we use the python3.8+ pickler, which supports this keyword.

**Comment by ogrisel** [comment]
@suquark @pcmoritz @pierreglaser please review my last commits.

Also feel free to comment on dropping Python 2 support:  #338.

**Comment by ogrisel** [comment]
Merged (because I want to work on another PR and conflicts on the changelog are annoying :)

Feel free to comment though.

**Pull request merged**
