### PR TITLE
Support for recursive functions inside closures

### PR DESCRIPTION
**Pull request by mehrdadn**
Adds the ability to reconstruct closures in distributions, such as CPython, that support `ctypes.pythonapi.PyCell_Set`.

### CODE REVIEW

**Comment by mehrdadn** [comment]
Note that this pull request is intended to fix issue #62.

**Comment by pcmoritz** [comment]
@mrocklin Can you have a look at the PR and merge it if you don't see problems? I hope it will also be helpful for dask!

**Comment by mrocklin** [comment]
Glad to see Ray folks contributing to cloudpickle, which has a strong tradition of being developed by essentially every parallel python computing project :)

FYI I'm currently somewhat slammed and so may not review this immediately.  However, I'm also not the main maintainer of this library (there are several of us that each do a little bit).

**Comment by mrocklin** [comment]
I wonder if @llllllllll has any interest in reviewing and helping out with cloudpickle?  This is very slightly in his realm of interest.

**Comment by pcmoritz** [comment]
Thanks for letting us know! It makes sense to distribute the development on many shoulders, given how many different corner cases there are and how complex it is to get all the details right :)

It is very unfortunate that there is so much complexity in the whole python pickling landscape, a more modern alternative like https://jsonpickle.github.io/ (maybe based on a good binary serialization format) would be great if there was a way to cover as much functionality as with (cloud)pickle.

**Comment by pitrou** [comment]
Superseded by PR #90.

**Pull request closed without merging**
