### PR TITLE
[NOMRG] test pickle5 + ray + refactored cloudpickle

### PR DESCRIPTION
**Pull request by pierreglaser**
This is a rebase of #370 with the newest changes in #368. in this PR, `ray`'s downstream build should run succesfully.
I'm making a temporary PR to not mess up #370 before I'm sure `ray` tests succeed.

### CODE REVIEW

**Comment by pierreglaser** [comment]
@jakirkham the failing test mentions a `TypeError` in the traceback. Looks similar to pitrou/pickle5-backport#19 no?

I'm trying to have `ray` use the latest `pickle5` by pre-installing `pickle5` on the CI before installing `ray`, so that `ray` does not use its pinned, vendored `pickle5`. But it does not seem to work...

**Comment by pierreglaser** [comment]
Alright. the `ray` downstream build is passing. That was instructive, as it made me realize that #370 extends the pure-python `Pickler` instead of the `C`-implemented `Pickler` if using `pickle5`.

**Comment by jakirkham** [comment]
> @jakirkham the failing test mentions a `TypeError` in the traceback. Looks similar to [pitrou/pickle5-backport#19](https://github.com/pitrou/pickle5-backport/issues/19) no?

Think that is fixed in `pickle5` 0.0.11+. Or at least PR ( https://github.com/pitrou/pickle5-backport/pull/20 ) fixed a similar issue for me.

> EDIT: actually, I'm not sure it's about that. Seems like an interaction with a custom registered reducer implemented by ray.

Yeah actually I knew the fix worked when I tried it, but I think more recent changes in PR ( https://github.com/cloudpipe/cloudpickle/pull/368 ) may have alleviated the underlying problem (as I had trouble reproducing the issue with an older `pickle5`). Tricky keeping track of code in multiple libraries/PRs 😅

**Comment by jakirkham** [comment]
> That was instructive, as it made me realize that #370 extends the pure-python `Pickler` instead of the `C`-implemented `Pickler` if using `pickle5`.

Interesting. Thanks for surfacing that. I'll take another look and see if we can fix it. 🙂

**Comment by pierreglaser** [comment]
> Interesting. Thanks for surfacing that. I'll take another look and see if we can fix it.

merging this PR inside #370 should do the trick, as I had to fix the issue I mentioned to make the test pass :)

**Comment by jakirkham** [comment]
Oh great! Thanks Pierre 😄

**Comment by pierreglaser** [comment]
Closing as this is superseeded by #370

**Pull request closed without merging**
