### PR TITLE
Include pickle load and loads into namespace

### PR DESCRIPTION
**Pull request by parnmatt**
Allow users to import just cloudpickle to dump and load pickled data.

cloudpickle can be a drop-in replacement for pickle, for basic
functionality `import cloudpickle as pickle`.

Issue Ref: #36

### CODE REVIEW

**Comment by rgbkrk** [comment]
Fine by me.

**Comment by ogrisel** [comment]
@rgbkrk you merged too quickly, we need a test for that.

**Comment by rgbkrk** [comment]
shame on me!

**Comment by parnmatt** [comment]
How would that test look like?

```python
def test_loads_namespace(self):
    obj = # something to pickle
    returned_obj = cloudpickle.loads(cloudpickle.dumps(obj))
    assertEqual(obj, returned_obj)
```

And something like that for a `load`/`dump` too?

**Comment by ogrisel** [comment]
That would do yes.

**Comment by jakirkham** [comment]
Test included in ( https://github.com/cloudpipe/cloudpickle/pull/38 ).

**Pull request merged**
