### PR TITLE
trigger downstream builds on issue comment

### PR DESCRIPTION
**Pull request by pierreglaser**
github workflows triggered by `pull requests` events actually make it clumsy to run conditional builds based on commit messages. 

Alternative proposal: rely on the github `IssueComment` event, and run those downstream builds when a comment such as `/run joblib` is added in a PR.

### CODE REVIEW

**Comment by pierreglaser** [comment]
github please run the ray downstream build.

**Comment by pierreglaser** [comment]
test

**Comment by ogrisel** [comment]
It's weird I do not see the new workflow in the actions tab: https://github.com/cloudpipe/cloudpickle/actions

**Comment by ogrisel** [comment]
Actually since this is not yet merged into a branch of this repo, this might be expected.

However I do not see it either on your own repo:

https://github.com/pierreglaser/cloudpickle/actions

**Comment by pierreglaser** [comment]
Maybe if I open an issue/PR on my fork?

**Comment by ogrisel** [comment]
Alternative idea:

Put a condition on the presence of a label on the PR. We could have a new set of labels such as `ci:downstream`, `ci:distributed`, `ci:nightly` and based on the presence of those labels on a given PR we would run the matching CI jobs on push events to that PR.

**Comment by ogrisel** [comment]
> Maybe if I open an issue/PR on my fork?

Yes you can try this. Maybe make a PR from a new branch that starts from `downstream-builds-pr-comment` into `downstream-builds-pr-comment`

**Comment by ogrisel** [comment]
As discussed here https://github.community/t5/GitHub-Actions/Issue-Comment-events-on-github-actions/td-p/34124 maybe the workflow is not active as long as it's not merged in the default branch of the repo (e.g. master).

Maybe you can create a new test repo (with a copy of the cloudpickle repo content) to test it and push directly to your master branch.

**Comment by ogrisel** [comment]
Cool. Don't worry of the core dev guard. Actually I think it would be good if contributors could trigger the downstream builds by themselves on their own PR.

If it's too troublesome to adapt the build scripts to work on issue comment events instead of push events because the context is too different, maybe you could reconsider my alternative suggestion that looks simpler to implement and "good enough":

https://github.com/cloudpipe/cloudpickle/pull/336#issuecomment-582330094

**Comment by pierreglaser** [comment]
Closing this as we ended up choosing another solution (#339 )

**Pull request closed without merging**
