### PR TITLE
Test that downstream builds are triggered when a PR is labeled with 'ci downstream'

### PR DESCRIPTION
**Pull request by pierreglaser**
test PR to check that the downstream projects tests are well ran when the label 'ci downstream' is set.

### CODE REVIEW

**Comment by ogrisel** [comment]
It seems to work nicely!

**Comment by pierreglaser** [comment]
The jobs react to their individual labels as well as to the "ci downstream" label. I think we're good.

**Comment by pierreglaser** [comment]
@ogrisel the conclusions from exploring the different webhooks of github-actions the support for conditional jobs on **Pull Request comming from forks** is just not there yet. I hope at some point in the future there will be a more natural way to achieve the same result as here.

**Comment by ogrisel** [comment]
The loky one had failed with a low level github actions error message. I restarted all of them (I could non only re-run failed jobs).

**Comment by pierreglaser** [comment]
All tests passed. We're good for a release soon :)

**Comment by ogrisel** [comment]
There was another low level github actions failure. Here is the message for the record:

```
GitHub.Services.WebApi.VssServiceResponseException: The resource cannot be found.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectAsync(VssConnection jobConnection)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

**Pull request closed without merging**
