### PR TITLE
WIP: Optionally use pickle5

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/cloudpipe/cloudpickle/issues/179

Optionally uses `pickle5` in `cloudpickle`.

### CODE REVIEW

**Comment by jakirkham** [comment]
Before doing more work here, would be curious to get people's thoughts on this approach 🙂

Does this generally seem reasonable? Or would we want to approach this in a different way?

**Comment by pierreglaser** [comment]
> Before doing more work here, would be curious to get people's thoughts on this approach

The general approach (*optionally* rely on `pickle5`) looks good to me. We should also add/modify an entry in the `CI` to test `cloudpickle` against `Python < 3.8` and `pickle5`. Thanks @jakirkham!

**Comment by jakirkham** [comment]
Have run into some test issues around `CellType` (added in Python 3.8) and other related things. Not sure if there is an easy way to bypass these sorts of issues (since they are not the primary focus here). Thoughts? 🙂

**Comment by pierreglaser** [comment]
With regards to the `types.CellType` issue: `cloudpickle_fast.py` was originally written for `Python 3.8+`, so if we want to use it for `Python < 3.8`, we have no choice but to make the reducers within `cloudpickle_fast.py` cross-version.

The clean way though would be to refactor the organization of the reducers in `cloudpickle`, many of which are duplicated between `cloudpickle.py` and `cloudpickle_fast.py`, so that both modules import the same ones. See #284. Maybe this PR is a good occasion to do this (within this PR or separately) :)

**Comment by ogrisel** [comment]
If we refactor the reducers, we should make a best effort to still make it possible to unpickle older pickles.

Even if this is not part of the cloudpickle public API (see the diclaimer for the scope of the project in the README) it would be great to preserve backward compat with previous version pickles if not too costly from a maintenance / tech debt point of view.

**Comment by pierreglaser** [comment]
That is a very good remark @ogrisel. Would the `deprecation` cycle I suggested in https://github.com/cloudpipe/cloudpickle/pull/359#discussion_r415684864 work for you? IMHO it achieves a good tradeoff between all the stakes (code complexity, user friendliness, contract of `cloudpickle`...)

**Comment by ogrisel** [comment]
+1 for deprecation warnings when possible.

**Comment by jakirkham** [comment]
Closing as this has been superseded by PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ).

**Pull request closed without merging**
