### PR TITLE
TST new subprocess-based tests

### PR DESCRIPTION
**Pull request by ogrisel**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looking good, want to bring this in as is? I'll be happy to submit the IPython kernel subtests after.

**Comment by ogrisel** [comment]
Let me squash the intermediate debug commits first.

**Comment by ogrisel** [comment]
Done, I think we can merge as is for now.

**Comment by ogrisel** [comment]
Thanks. @rgbkrk Feel free to refactor as a class `PickleEcho` with a `pickle_depickle` method that does `pickle.loads(cloudpickle.dumps(obj))` in the base implementation and a `SubprocessPickleEcho` subclass with this implementation and refactor the test cases to have both implementation run on the full test suite and make it possible to derive further for integration tests (e.g. for the IPython kernel).

**Pull request merged**
