### PR TITLE
MINOR: Fix formatting issues

### PR DESCRIPTION
**Pull request by BryanCutler**
This fixes a few small formatting issues I found while working on https://github.com/apache/spark/pull/20373

### CODE REVIEW

**Comment by BryanCutler** [comment]
I ran py.test locally to verify this patch with Python 2.7.  I know some of this changes can be subjective, so feel free to take some or none, but I figured it might help to clean up a little.  Thanks!

**Comment by BryanCutler** [comment]
cc @holdenk

**Comment by rgbkrk** [comment]
Looks great, thanks for also getting PySpark up to date.

**Comment by BryanCutler** [comment]
Thanks @rgbkrk !  It was good to get familiar with this code, I'll hopefully be able to make some more contributions in the future

**Pull request merged**
