### PR TITLE
Fix downstream CI

### PR DESCRIPTION
**Pull request by ogrisel**
- bump up the python version used to run those tests;
- add a missing dependency (aihttp) for distributed.

### CODE REVIEW

**Comment by ogrisel** [comment]
Apparently this is caused by this error when installing the dev branch of `distributed`:

```
 ERROR: Ignored the following versions that require a different python version: 2022.2.1 Requires-Python >=3.8; 2022.3.0 Requires-Python >=3.8; 2022.4.0 Requires-Python >=3.8; 2022.4.1 Requires-Python >=3.8; 2022.4.2 Requires-Python >=3.8; 2022.5.0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement dask==2022.05.0 (from distributed) (from versions: 0.7.4.linux-x86_64, 0.7.5.linux-x86_64, 0.7.6.linux-x86_64, 0.8.1.macosx-10.5-x86_64, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.0rc1, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.20.0, 0.20.1, 0.20.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.10.1, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.16.0, 2.17.0, 2.17.1, 2.17.2, 2.18.0, 2.18.1, 2.19.0, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.30.0, 2020.12.0, 2021.1.0, 2021.1.1, 2021.2.0, 2021.3.0, 2021.3.1, 2021.4.0, 2021.4.1, 2021.5.0, 2021.5.1, 2021.6.0, 2021.6.1, 2021.6.2, 2021.7.0, 2021.7.1, 2021.7.2, 2021.8.0, 2021.8.1, 2021.9.0, 2021.9.1, 2021.10.0, 2021.11.0, 2021.11.1, 2021.11.2, 2021.12.0, 2022.1.0, 2022.1.1, 2022.2.0)
ERROR: No matching distribution found for dask==2022.05.0
```

We probably need to upgrade the Python version to run the distributed tests.

**Comment by ogrisel** [comment]
The 3.11 failure will be fixed in a concurrent PR.

**Comment by ogrisel** [comment]
There are a couple of failing tests in distributed, I am not sure whether they are related to cloudpickle or not. Any idea @jakirkham or @mrocklin?

I will merge this anyway to get fix the test config itself but it would be great to know what to do to fix the failing tests.

**Comment by jakirkham** [comment]
cc @jrbourbeau (in case anything sticks out to you)

**Comment by jakirkham** [comment]
Wonder if this is related to PR ( https://github.com/dask/distributed/pull/6007 )

**Comment by jakirkham** [comment]
Filed issue ( https://github.com/dask/distributed/issues/6403 ) to track/improve visibility

**Pull request merged**
